baseURL = "http://www.mukkund1996.github.io"
title = "Pasan Kalansooriya"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Pasan Kalansooriya"
description = "Pasan Kalansooriya's personal website"
keywords = "blog,developer,personal"
info = ["final-year CSE undergrad", "Tech Enthusiast", "Blogger"]
avatarURL = "https://i.postimg.cc/ncbQQx4D/1665799174485.jpg"
dateFormat = "January 2, 2006"
since = 2018
favicon_32 = "images/favicon-32x32.png"
favicon_16 = "images/favicon-16x16.png"

commit = "https://github.com/pasan-SK"
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = ["css/custom.css"]
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = ["scss/custom.scss"]
# Custom JS
customJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/pasan-SK"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/pasan-kalansooriya-825b54213/"

[[params.social]]
name = "Medium"
icon = "fa fa-2x fa-medium"
weight = 3
url = "https://medium.com/@pasanSK"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "about"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "projects"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "blog"
weight = 3
url = "posts/"

[[languages.en.menu.main]]
name = "contact me"
weight = 4
url = "about/#want-to-connect"